### ISSUE TITLE
Default CodeChat.css includes non-existing html4css1.css

### ISSUE THREAD

**Issue by htgoebel** [bjones1/CodeChat#12]
The `CodeChat.css` file contained in this archive includes non-existing `html4css1.css`. Is this file required?

1. Sphinx 2.0 seems to default to HTML 5 anyway, since [option `html_experimental_html5_writer` is deproicated](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-html_experimental_html5_writer)
2. Docutils (which provide `html4css1.css`) do not provide any htm5 stylesheet. Try `find . -iname \*html5\*`  and `find . -iname \*.css`.

**Comment by bjones1** [comment]
It's required for non-Sphinx builds -- when docutils produces the output, rather than Sphinx. As you say, docutils doesn't provide any HTML5 stylesheets. It's ignored when using Sphinx, since the files doesn't exist. I suppose I could provide two copies of `CodeChat.css`, one with the include and one without, but the solution seems worse than the problem.
